version: '3.8'

services:
  springboot-app:
    image: spring-app-1
    container_name: springboot-app
    env_file:
      - .env
    ports:
      - "8080:8080"
    depends_on:
      - mongo

  mongo:
    image: mongo:latest
    container_name: mongo
    ports:
      - "27017:27017"